version: "3"
services:
  db:
    image: postgres:9.4
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: "editor"
      POSTGRES_PASSWORD: "N0A8KHWWHMjRBTrc8UjL"

  engine:
    build: Engine
    image: servicecutter/engine
    expose:
     - 8090
    ports:
     - "8090:8090"
    depends_on:
     - db

