package ch.hsr.servicestoolkit.model;

public enum CriterionType {
	SAME_ENTITIY, AGGREGATED_ENTITY, COMPOSITION_ENTITY, INHERITANCE, WRITE_BUSINESS_TRANSACTION, READ_BUSINESS_TRANSACTION, READ_WRITE_BUSINESS_TRANSACTION;

}
